eks_release_url: https://distro.eks.amazonaws.com/kubernetes-1-31/kubernetes-1-31-eks-6.yaml
eks_release_arch: amd64 # amd64 || arm64
eks_release_os: linux

containerd_version: 1.7.22
containerd_os: linux
containerd_arch: amd64 # amd64 || arm64

runc_version: 1.1.14
runc_arch: amd64 # amd64 || arm64

cni_plugins_version: 1.5.1
cni_plugins_arch: amd64 # amd64 || arm64
cni_plugins_os: linux

crictl_version: 1.31.1
crictl_arch: amd64 # amd64 || arm64
crictl_os: linux